# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master
 
pages:
  before_script:
    - 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # - sed -i config.toml -e "s/!GMAP_API_KEY!/"$GMAP_API_KEY"/g"
    - sed -i config.toml -e "s/!CONTACT_FORM_ACTION!/${CONTACT_FORM_ACTION}/g"
    - sed -i config.toml -e "s/!GMAP_API_KEY!/${GMAP_API_KEY}/g"
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
