# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - apt-get update -qq
  - apt-get install -qq git # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$DEPLOY_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'

test:
  script:
    - hugo
  except:
    - master
 
pages:
  before_script:
    # - sed -i config.toml -e "s/!GMAP_API_KEY!/"$GMAP_API_KEY"/g"
    - sed -i config.toml -e "s/!CONTACT_FORM_ACTION!/${CONTACT_FORM_ACTION}/g"
    - sed -i config.toml -e "s/!GMAP_API_KEY!/${GMAP_API_KEY}/g"
  script:
    - hugo
  artifacts:
    paths:
      - public
  only:
    - master
