# This file is a template, and might need editing before it works on your project.
---
# All available Hugo versions are listed here:
# https://gitlab.com/pages/hugo/container_registry
image: registry.gitlab.com/pages/hugo/hugo_extended

variables:
  GIT_SUBMODULE_STRATEGY: recursive

test:
  script:
    - hugo
  except:
    - master

pages:
  script:
    - hugo
    - sed -i 's/!GMAP_API_KEY!/$GMAP_API_KEY/g' config.toml
  artifacts:
    paths:
      - public
  only:
    - master
